### ISSUE TITLE
Duplicated with AXI_package

### ISSUE THREAD

**Issue by 25077667** [daven3302/NSYSU_Project#1]
https://github.com/daven3302/NSYSU_Project/blob/56427f8c7ecabfa817a5088688ad9cd0cb0a2c69/router.h#L17:L23

It is duplicated with AXI_stream_package.
Would you like to wrap it like:
class AXI4_Stream_protocal {
 ...
 unsigned TREADY : 1;
AXI4_Stream_package data;
};

**Comment by daven3302** [comment]
resolved
